
# A string used as a project reference
project_id = "rdzwpiokpyssqhnfiqrt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public", "supabase_functions"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true
ip_address = []

[studio]
enabled = true
port = 54323
api_url = "https://api.supabase.com"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "http://localhost:5173", "https://supabase.com/dashboard/project/_", "capacitor://localhost", "http://localhost"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = false

[auth.external.github]
enabled = true
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[experimental]
traces_path = "./traces"

[edge_functions]
enabled = true
port = 54323

[functions.create-onboard-submissions-bucket]
verify_jwt = false
